version: '3.7'

services:
  application:
    container_name: etu-utt-api
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
