version: '3'

services:

  application:
    build:
      target: development
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run start:dev"
    
  database:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
