import { Language, Translation as RawTranslation } from '@/prisma/build/client';

export {
  Prisma,
  PrismaClient,
  UserType,
  Sex,
  AddressPrivacy,
  Language,
  Permission,
  ImageMediaPreset,
  TimetableEntryType,
  User as RawUser,
  UserInfos as RawUserInfos,
  TimetableEntry as RawTimetableEntry,
  TimetableGroup as RawTimetableGroup,
  TimetableEntryOverride as RawTimetableEntryOverride,
  UserUeSubscription as RawUserUeSubscription,
  UTTBranch as RawBranch,
  UTTBranchOption as RawBranchOption,
  Semester as RawSemester,
  Ue as RawUe,
  Ueof as RawUeof,
  UeCredit as RawUeCredit,
  UeCreditCategory as RawCreditCategory,
  UeofInfo as RawUeofInfo,
  UeWorkTime as RawUeWorkTime,
  UeStarVote as RawUeStarVote,
  UeStarCriterion as RawUeStarCriterion,
  UeComment as RawUeComment,
  UeCommentReply as RawUeCommentReply,
  UeCommentUpvote as RawUeCommentUpvote,
  UeAnnalType as RawAnnalType,
  UeAnnal as RawAnnal,
  UeCourse as RawUeCourse,
  UserMailsPhones as RawUserMailsPhones,
  UserSocialNetwork as RawUserSocialNetwork,
  UserPreference as RawUserPreference,
  UserAddress as RawUserAddress,
  UserBranchSubscription as RawUserBranchSubscription,
  Asso as RawAsso,
  AssoMembershipRole as RawAssoMembershipRole,
  AssoMembership as RawAssoMembership,
  AssoMembershipPermission as RawAssoMembershipPermission,
  UserHomepageWidget as RawHomepageWidget,
  UserPrivacy as RawUserPrivacy,
  ApiApplication as RawApiApplication,
  ApiKey as RawApiKey,
  ImageMedia as RawImageMedia,

} from '@/prisma/build/client';

export { RawTranslation };
export type Translation = Pick<Partial<RawTranslation>, Language>;
