import { Language, Translation as RawTranslation } from '@prisma/client';

export {
  User as RawUser,
  UserInfos as RawUserInfos,
  TimetableEntry as RawTimetableEntry,
  TimetableGroup as RawTimetableGroup,
  TimetableEntryOverride as RawTimetableEntryOverride,
  UserUeSubscription as RawUserUeSubscription,
  UTTBranch as RawBranch,
  UTTBranchOption as RawBranchOption,
  Semester as RawSemester,
  Ue as RawUe,
  UeCredit as RawUeCredit,
  UeCreditCategory as RawCreditCategory,
  UeInfo as RawUeInfo,
  UeWorkTime as RawUeWorkTime,
  UeStarVote as RawUeStarVote,
  UeStarCriterion as RawUeStarCriterion,
  UeComment as RawUeComment,
  UeCommentReply as RawUeCommentReply,
  UeCommentUpvote as RawUeCommentUpvote,
  UeAnnalType as RawAnnalType,
  UeAnnal as RawAnnal,
  UserMailsPhones as RawUserMailsPhones,
  UserSocialNetwork as RawUserSocialNetwork,
  UserPreference as RawUserPreference,
  UserAddress as RawUserAddress,
  UserBranchSubscription as RawUserBranchSubscription,
  Asso as RawAsso,
  AssoMembershipRole as RawAssoMembershipRole,
  AssoMembership as RawAssoMembership,
  UserHomepageWidget as RawHomepageWidget,
  UserPrivacy as RawUserPrivacy,
  ApiApplication as RawApiApplication,
  ApiKey as RawApiKey,
} from '@prisma/client';

export { RawTranslation };
export type Translation = Pick<Partial<RawTranslation>, Language>;
