export {
  User as RawUser,
  UserInfos as RawUserInfos,
  TimetableEntry as RawTimetableEntry,
  TimetableGroup as RawTimetableGroup,
  TimetableEntryOverride as RawTimetableEntryOverride,
  UserUESubscription as RawUserUESubscription,
  Semester as RawSemester,
  UTTBranch as RawBranch,
  UTTBranchOption as RawBranchOption,
  UECreditCategory as RawCreditCategory,
  UE as RawUE,
  UEComment as RawUEComment,
  UEStarCriterion as RawUEStarCriterion,
  UEStarVote as RawUEStarVote,
} from '@prisma/client';
