import { IsAlphanumeric, IsDate, IsEnum, IsNotEmpty, IsNumber, IsOptional, IsString } from 'class-validator';
import { IsPositive } from 'class-validator';
import { Type } from 'class-transformer';
import { Sex } from '../../../prisma/types';
import { ApiProperty } from '@nestjs/swagger';

export default class AuthSignUpReqDto {
  @IsString()
  @IsNotEmpty()
  @ApiProperty({ description: 'Token that has been generated by route "POST /auth/cas/sign-in"' })
  registerToken: string;
}
