import {IsInt, IsNotEmpty, IsString} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import {Type} from "class-transformer";

export default class AuthCasSignUpReqDto {
  @IsString()
  @IsNotEmpty()
  @ApiProperty({ description: 'Token that has been generated by route "POST /auth/cas/sign-in"' })
  registerToken: string;

  @IsInt()
  @Type(() => Number)
  @ApiProperty({ description: 'How much time the generated token should be valid' })
  tokenExpiresIn?: number;
}
