import { IsInt, IsNotEmpty, IsString } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';

export default class CreateApiKeyReqDto {
  @IsString()
  @IsNotEmpty()
  @ApiProperty({
    description: 'Token that has been generated by route "POST /auth/cas/sign-in" or "POST /auth/sign-in"',
  })
  token: string;
}
