name: CI
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  # lint:
  #   runs-on: self-hosted
  #   strategy:
  #     matrix:
  #       node-version: [18]
  #   steps: 
  #     - uses: actions/checkout@v4
  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 9
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #         cache: 'pnpm'        
  #     - run: pnpm install --frozen-lockfile
  #     - run: pnpm pnpx prisma generate
  #     - run: pnpm lint

  # build:
  #   runs-on: self-hosted
  #   steps: 
  #     - uses: actions/checkout@v4
  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 9
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #         cache: 'pnpm'        
  #     - run: pnpm install --frozen-lockfile
  #     - run: pnpm pnpx prisma generate
  #     - run: pnpm build

  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18]
    env:
      DATABASE_URL: mysql://dev:dev@localhost:3306/etuutt_test
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'dev'
          MYSQL_PASSWORD: 'dev'
          MYSQL_DATABASE: etuutt_test
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306:3306
        options: --name mariadb --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'        
      - run: pnpm install --frozen-lockfile
      - run: cp .env.test.dist .env.test
      - run: pnpm test:db:reset
      - run: pnpm test:instantfail

  cov:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18]
    env:
      DATABASE_URL: mysql://dev:dev@localhost:3306/etuutt_test
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'dev'
          MYSQL_PASSWORD: 'dev'
          MYSQL_DATABASE: etuutt_test
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306:3306
        options: --name mariadb --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=5

    steps: 
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'        
      - run: pnpm install --frozen-lockfile
      - run: cp .env.test.dist .env.test
      - run: pnpm test:db:reset
      - run: pnpm test:cov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}